### ISSUE TITLE
ETag caching

### ISSUE THREAD

**Issue by Noah-Huppert** [Noah-Huppert/crime-map#10]
Calculate the ETag value of endpoint results. Then require clients to send this value to determine if they have the latest version. 

Limit the number of un-cached requests per token to some very low number. Don't let a token query the same endpoint, with the same parameters, more than 5 (?) times.

**Comment by Noah-Huppert** [comment]
Maybe implement via a general middleware for cachable endpoints.  


Which would take into account the request path and the included parameters.  

Could cache all this in Redis.  

Only implement if caching is needed.

**Comment by Noah-Huppert** [comment]
If the client makes too many requests without an ETag for the same element: make sure to provide the ETag value, so the user can still fetch the data, and has to change their behavior.

**Comment by catvec** [comment]
#11 provides a better solution
